#CREACION DE LA BASE DE DATOS Y DECLARANDO SU USO
CREATE DATABASE bebidas;
USE bebidas;

#CREACION DE TABLAS
CREATE TABLE tbClientes(
DNI VARCHAR (15) PRIMARY KEY,
NOMBRE VARCHAR (50),
APELLIDO VARCHAR (50),
DIRECCION1 VARCHAR (50),
BARRIO VARCHAR (50),
CIUDAD VARCHAR (50),
PROVINCIA VARCHAR (50),
CP VARCHAR (10),
EDAD SMALLINT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUMEN_COMPRA FLOAT,
PRIMERA_COMPRA BIT (1)
);

CREATE TABLE tbProductos(
PRODUCTOS VARCHAR (20),
NOMBRE VARCHAR (100),
ENVASE VARCHAR (50),
VOLUMEN VARCHAR (20),
SABOR VARCHAR (50),
PRECIO FLOAT
);

CREATE TABLE tbVendedores(
MATRICULA VARCHAR (5),
NOMBRE VARCHAR (100),
APELLIDO VARCHAR (100),
PORCENTAJE_COMISION FLOAT
);

CREATE TABLE TABLA_DE_VENDEDORES2 (
    MATRICULA varchar(5), 
    NOMBRE varchar(100), 
    PORCENTAJE_COMISION float);

CREATE TABLE tbproducto
(PRODUCTO VARCHAR (20) PRIMARY KEY,
NOMBRE VARCHAR (150) ,
ENVASE VARCHAR (50) ,
TAMANO VARCHAR (50) ,
SABOR VARCHAR (50) ,
PRECIO_LISTA FLOAT);

#ELIMINO TABLA
DROP TABLE TABLA_DE_VENDEDORES2;
DROP TABLE tbProductos;

#AGREGANDO REGISTROS TABLA VENDEDORES
INSERT INTO tbVendedores (MATRICULA, NOMBRE, APELLIDO, PORCENTAJE_COMISION) 
VALUES ("00233", "JOAN GERALDO", "DE LA FONSECA", 0.10);
INSERT INTO tbVendedores (MATRICULA, NOMBRE, APELLIDO, PORCENTAJE_COMISION) 
VALUES ("00235", "MARCIO", "ALMEIDA SILVA", 0.08);
INSERT INTO tbVendedores (MATRICULA, NOMBRE, APELLIDO, PORCENTAJE_COMISION) 
VALUES ("00236", "CLAUDIA", "MORAIS", 0.08);
INSERT INTO tbVendedores (MATRICULA, NOMBRE, APELLIDO, PORCENTAJE_COMISION, 
FDADMISION, VACACIONES) 
VALUES ("00237", "ROBERTA", "MARTINS", 0.11, "2017-03-18", 1);
INSERT INTO tbVendedores (MATRICULA, NOMBRE, APELLIDO, PORCENTAJE_COMISION, 
FDADMISION, VACACIONES) 
VALUES ("00238", "PERICLES", "ALVES", 0.11, "2016-08-21", 0);

#AGREGANDO REGISTROS TABLA PRODUCTOS
INSERT INTO tbProductos (PRODUCTOS, NOMBRE, ENVASE, VOLUMEN, SABOR, PRECIO) VALUES ("773912", "CLEAN", "BOTELLA PET", "1 LITRO", "NARANJA", 8.01);
INSERT INTO tbProductos (PRODUCTOS, NOMBRE, ENVASE, VOLUMEN, SABOR, PRECIO) VALUES ("838819", "CLEAN", "BOTELLA PET", "1.5 LITROS", "NARANJA", 12.01);
INSERT INTO tbProductos (PRODUCTOS, NOMBRE, ENVASE, VOLUMEN, SABOR, PRECIO) VALUES ("1037797", "CLEAN", "BOTELLA PET", "2 LITROS", "NARANJA", 16.01);
INSERT INTO tbProductos (PRODUCTOS, NOMBRE, ENVASE, VOLUMEN, SABOR, PRECIO) VALUES ("8128292", "CLEAN", "LATA", "350 ML", "NARANJA", 2.81);
INSERT INTO tbProductos (PRODUCTOS, NOMBRE, ENVASE, VOLUMEN, SABOR, PRECIO) VALUES ("695594", "FESTIVAL DE SABORES", "BOTELLA PET", "1.5 LITROS", "ASAI", 18.51);
INSERT INTO tbProductos (PRODUCTOS, NOMBRE, ENVASE, VOLUMEN, SABOR, PRECIO) VALUES ("1041119", "LINEA CITRUS", "VIDRIO", "700 ML", "LIMA", 4.90);
INSERT INTO tbProductos (PRODUCTOS, NOMBRE, ENVASE, VOLUMEN, SABOR, PRECIO) VALUES ("43224920", "MALENA DOMINGUEZ", "29/03/2001", "22", "CHILENA", 8.50);

INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('773912', 'Clean', '1 Litro', 'Naranja', 'Botella PET', 8.01);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('838819', 'Clean', '1,5 Litros', 'Naranja', 'Botella PET', 12.01);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('1037797', 'Clean', '2 Litros', 'Naranja', 'Botella PET', 16.01);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('812829', 'Clean', '350 ml', 'Naranja', 'Lata', 2.81);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('479745', 'Clean', '470 ml', 'Naranja', 'Botella de Vidrio', 3.77);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('695594', 'Festival de Sabores', '1,5 Litros', 'Asaí', 'Botella PET', 28.51);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('243083', 'Festival de Sabores', '1,5 Litros', 'Maracuyá', 'Botella PET', 10.51);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('1022450', 'Festival de Sabores', '2 Litros', 'Asái', 'Botella PET', 38.01);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('231776', 'Festival de Sabores', '700 ml', 'Asaí', 'Botella de Vidrio', 13.31);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('723457', 'Festival de Sabores', '700 ml', 'Maracuyá', 'Botella de Vidrio', 4.91);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('746596', 'Light', '1,5 Litros', 'Sandía', 'Botella PET', 19.51);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('1040107', 'Light', '350 ml', 'Sandía', 'Lata', 4.56);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('1002334', 'Línea Citrus', '1 Litro', 'Lima/Limón', 'Botella PET', 7);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('1088126', 'Línea Citrus', '1 Litro', 'Limón', 'Botella PET', 7);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('1041119', 'Línea Citrus', '700 ml', 'Lima/Limón', 'Botella de Vidrio', 4.9);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('1042712', 'Línea Citrus', '700 ml', 'Limón', 'Botella de Vidrio', 4.9);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('520380', 'Pedazos de Frutas', '1 Litro', 'Manzana', 'Botella PET', 12.01);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('788975', 'Pedazos de Frutas', '1,5 Litros', 'Manzana', 'Botella PET', 18.01);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('229900', 'Pedazos de Frutas', '350 ml', 'Manzana', 'Lata', 4.21);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('1101035', 'Refrescante', '1 Litro', 'Frutilla/Limón', 'Botella PET', 9.01);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('1086543', 'Refrescante', '1 Litro', 'Mango', 'Botella PET', 11.01);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('326779', 'Refrescante', '1,5 Litros', 'Mango', 'Botella PET', 16.51);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('826490', 'Refrescante', '700 ml', 'Frutilla/Limón', 'Botella de Vidrio', 6.31);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('1096818', 'Refrescante', '700 ml', 'Mango', 'Botella de Vidrio', 7.71);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('394479', 'Sabor da Montaña', '700 ml', 'Cereza', 'Botella de Vidrio', 8.41);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('783663', 'Sabor da Montaña', '700 ml', 'Frutilla', 'Botella de Vidrio', 7.71);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('1000889', 'Sabor da Montaña', '700 ml', 'Uva', 'Botella de Vidrio', 6.31);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('544931', 'Verano', '350 ml', 'Limón', 'Lata', 2.46);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('235653', 'Verano', '350 ml', 'Mango', 'Lata', 3.86);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('1051518', 'Verano', '470 ml', 'Limón', 'Botella de Vidrio', 3.3);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('1078680', 'Verano', '470 ml', 'Mango', 'Botella de Vidrio', 5.18);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('1004327', 'Vida del Campo', '1,5 Litros', 'Sandía', 'Botella PET', 19.51);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('1013793', 'Vida del Campo', '2 Litros', 'Cereza/Manzana', 'Botella PET', 24.01);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('290478', 'Vida del Campo', '350 ml', 'Sandía', 'Lata', 4.56);
INSERT INTO tbProducto (PRODUCTO, NOMBRE, TAMANO, SABOR, ENVASE, PRECIO_LISTA) VALUES ('1002767', 'Vida del Campo', '700 ml', 'Cereza/Manzana', 'Botella de Vidrio', 8.41);

#AGREGANDO REGISTROS A LA TABLA CLIENTES
INSERT INTO tbClientes (DNI, NOMBRE, APELLIDO, DIRECCION1, BARRIO, CIUDAD, PROVINCIA, CP, EDAD, SEXO, LIMITE_CREDITO, VOLUMEN_COMPRA, PRIMERA_COMPRA, FDNAC) 
VALUES ("38786261", "MAXIMILIANO", "NAHUELANCA", "VIDAL 848", "AGP", "RIO GRANDE", "TIERRA DEL FUEGO","9420", 27, "M", 150000, 2000, 0, "1995-09-05");
INSERT INTO tbclientes (DNI, NOMBRE, APELLIDO, DIRECCION1, BARRIO, CIUDAD, PROVINCIA, CP, EDAD, SEXO, LIMITE_CREDITO, VOLUMEN_COMPRA, PRIMERA_COMPRA, FDNAC) 
VALUES ("40658488", "NICOLAS", "OYARZO", "BROWN 56", "CENTRO", "RIO GRANDE", "TIERRA DEL FUEGO","9420", 29, "M", 180000, 2500, 0, "1993-07-15");
INSERT INTO tbclientes (DNI, NOMBRE, APELLIDO, DIRECCION1, BARRIO, CIUDAD, PROVINCIA, CP, EDAD, SEXO, LIMITE_CREDITO, VOLUMEN_COMPRA, PRIMERA_COMPRA, FDNAC) 
VALUES ('7771579779', "Marcelo", "Perez", 'F.C. de Cuernavaca 13', 'Carola', 'Ciudad de México', 'CDMX', '88202912', 29, 'M', 120000, 200000, 1, '1992-01-25');
INSERT INTO tbclientes (DNI, NOMBRE, APELLIDO, DIRECCION1, BARRIO, CIUDAD, PROVINCIA, CP, EDAD, SEXO, LIMITE_CREDITO, VOLUMEN_COMPRA, PRIMERA_COMPRA, FDNAC) 
VALUES ('5576228758', "Pedro", "Olivera", 'Pachuca 75', 'Condesa', 'Ciudad de México', 'CDMX', '88192029', 25, 'F', 70000, 160000, 1, '1995-01-14');
INSERT INTO tbclientes (DNI, NOMBRE, APELLIDO, DIRECCION1, BARRIO, CIUDAD, PROVINCIA, CP, EDAD, SEXO, LIMITE_CREDITO, VOLUMEN_COMPRA, PRIMERA_COMPRA, FDNAC) 
VALUES ('8502682733', "Luis", "Silva", 'Prol. 16 de Septiembre 1156', 'Contadero', 'Ciudad de México', 'CDMX', '82122020', 25, 'M', 110000, 190000, 0,'1995-01-07');
INSERT INTO tbclientes (DNI, NOMBRE, APELLIDO, DIRECCION1, BARRIO, CIUDAD, PROVINCIA, CP, EDAD, SEXO, LIMITE_CREDITO, VOLUMEN_COMPRA, PRIMERA_COMPRA, FDNAC) 
VALUES ('1471156710', "Erica", "Carvajo", 'Heriberto Frías 1107', 'Del Valle', 'Ciudad de México', 'CDMX', '80012212', 30, 'F', 170000, 245000, 0, '1990-01-01');
INSERT INTO tbclientes (DNI, NOMBRE, APELLIDO, DIRECCION1, BARRIO, CIUDAD, PROVINCIA, CP, EDAD, SEXO, LIMITE_CREDITO, VOLUMEN_COMPRA, PRIMERA_COMPRA, FDNAC) 
VALUES ('3623344710', "Marcos", "Rosas", 'Av. Universidad', 'Del Valle', 'Ciudad de México', 'CDMX', '22002012', 26, 'M', 110000, 220000, 1, '1995-01-13');
INSERT INTO tbclientes (DNI, NOMBRE, APELLIDO, DIRECCION1, BARRIO, CIUDAD, PROVINCIA, CP, EDAD, SEXO, LIMITE_CREDITO, VOLUMEN_COMPRA, PRIMERA_COMPRA, FDNAC) 
VALUES ('50534475787', "Abel", "Pintos", 'Carr. México-Toluca 1499', 'Cuajimalpa', 'Ciudad de México', 'CDMX', '22000212', 25, 'M', 170000, 260000, 0, '1995-01-11');
INSERT INTO tbclientes (DNI, NOMBRE, APELLIDO, DIRECCION1, BARRIO, CIUDAD, PROVINCIA, CP, EDAD, SEXO, LIMITE_CREDITO, VOLUMEN_COMPRA, PRIMERA_COMPRA, FDNAC) 
VALUES ('5840119709', "Gabriel", "Roca", 'Eje Central Lázaro Cárdenas 911', 'Del Valle', 'Ciudad de México', 'CDMX', '80010221', 36, 'M', 140000, 210000, 1, '1985-01-16');
INSERT INTO tbclientes (DNI, NOMBRE, APELLIDO, DIRECCION1, BARRIO, CIUDAD, PROVINCIA, CP, EDAD, SEXO, LIMITE_CREDITO, VOLUMEN_COMPRA, PRIMERA_COMPRA, FDNAC) 
VALUES ('94387575700', "Walter", "Soruco", 'Calz. de Tlalpan 2980', 'Ex Hacienda Coapa', 'Ciudad de México', 'CDMX', '22000201', 31, 'M', 60000, 120000, 1, '1989-01-20');
INSERT INTO tbclientes (DNI, NOMBRE, APELLIDO, DIRECCION1, BARRIO, CIUDAD, PROVINCIA, CP, EDAD, SEXO, LIMITE_CREDITO, VOLUMEN_COMPRA, PRIMERA_COMPRA, FDNAC) 
VALUES ('8719655770', "Carlos", "Santivañez", 'Calz. del Hueso 363', 'Floresta Coyoacán', 'Ciudad de México', 'CDMX', '81192002', 37, 'M', 200000, 240000, 0 , '1983-01-20');
INSERT INTO tbclientes (DNI, NOMBRE, APELLIDO, DIRECCION1, BARRIO, CIUDAD, PROVINCIA, CP, EDAD, SEXO, LIMITE_CREDITO, VOLUMEN_COMPRA, PRIMERA_COMPRA, FDNAC) 
VALUES ('5648641702', "Paolo", "Mendez", 'Martires de Tacubaya 65', 'Héroes de Padierna', 'Ciudad de México', 'CDMX', '21002020', 29, 'M', 120000, 220000, 0, '1991-01-30');
INSERT INTO tbclientes (DNI, NOMBRE, APELLIDO, DIRECCION1, BARRIO, CIUDAD, PROVINCIA, CP, EDAD, SEXO, LIMITE_CREDITO, VOLUMEN_COMPRA, PRIMERA_COMPRA, FDNAC) 
VALUES ('492472718', "Jorge", "Castro", 'Federal México-Toluca 5690', 'Locaxco', 'Ciudad de México', 'CDMX', '22012002', 26, 'M', 75000, 95000, 1, '1994-01-19');

#CORRIGIENDO REGISTROS
UPDATE tbProductos SET PRODUCTOS = "812829" WHERE VOLUMEN = "350 ML";
UPDATE tbProductos SET PRECIO = 28.51 WHERE PRODUCTOS = "695594";
UPDATE tbProductos SET SABOR = "LIMA/LIMON" WHERE PRODUCTOS = "1041119";
UPDATE tbVendedores SET PORCENTAJE_COMISION = 0.11 WHERE MATRICULA = "00236";
UPDATE tbVendedores SET APELLIDO = "FONSECA JUNIOR" WHERE MATRICULA = "00233";
UPDATE tbVendedores SET FDADMISION = "2013-09-17" WHERE MATRICULA = "00236";
UPDATE tbVendedores SET FDADMISION = "2014-08-15" WHERE MATRICULA = "00235";
UPDATE tbVendedores SET VACACIONES = 0 WHERE MATRICULA = "00235";
UPDATE tbVendedores SET VACACIONES = 1 WHERE MATRICULA = "00236";

#ELIMINANDO REGISTROS
DELETE FROM tbProductos WHERE PRODUCTOS = "773912";
DELETE FROM tbVendedores WHERE MATRICULA = "00233";
DELETE FROM tbProductos WHERE PRODUCTOS = "43224920";

#INCLUYENDO CLAVE PRIMARA - PK
ALTER TABLE tbProductos ADD PRIMARY KEY (PRODUCTOS);
ALTER TABLE tbclientes ADD PRIMARY KEY (DNI); #YA LO TENIA CREADO
ALTER TABLE tbVendedores ADD PRIMARY KEY (MATRICULA);

#AGREGANDO NUEVA COLUMNA (CAMPO) A TABLA CLIENTES
ALTER TABLE tbClientes ADD COLUMN (FDNAC DATE);

#AGREGANDO NUEVA COLUMNA (CAMPO) A TABLA VENDEDORES
ALTER TABLE tbVendedores ADD COLUMN (FDADMISION DATE);
ALTER TABLE tbVendedores ADD COLUMN (VACACIONES BIT(1));

#GENERANDO DISTINTAS VISUALIZACIONES CON SELECT
SELECT NOMBRE, APELLIDO, EDAD FROM TBCLIENTES;
SELECT NOMBRE, MATRICULA FROM TBVENDEDORES;

#AGREGANDO UN ALIAS A LAS COLUMNAS PARA VISUALIZAR
SELECT NOMBRE AS "Name", APELLIDO AS Surname, EDAD AS Años FROM TBCLIENTES;

#PODEMOS LIMITAR LA CANTIDAD DE REGISTROS QUE NOS DEVUELVE
SELECT NOMBRE, APELLIDO, EDAD FROM TBCLIENTES LIMIT 5;

#PODEMOS FILTRAR EL RESULTADO DE UNA BUSQUEDA CON UN WHERE
SELECT * FROM tbProducto WHERE ENVASE = "BOTELLA DE VIDRIO";
SELECT * FROM tbVendedores WHERE NOMBRE = "CLAUDIA";

#PODEMOS FILTRAR RESULTADOS CON SIGNOS MAYOR O MENOR QUE < > <= =>
#PARA BUSCAR "DIFERENTE QUE..." EL SIGNO ES <>
SELECT * FROM tbClientes WHERE EDAD < 27;
SELECT * FROM tbClientes WHERE EDAD <> 25;
SELECT * FROM tbVendedores WHERE porcentaje_comision > 0.10;

#PODEMOS FILTRAR LOS RESULTADOS CON UN RANGO - BETWEEN (ENTRE) ESTO Y AQUELLO.
SELECT * FROM tbClientes WHERE EDAD BETWEEN 20 AND 29;

#FILTRANDO FECHAS
SELECT * FROM tbClientes WHERE YEAR(FDNAC) = 1995; #POR AÑO
SELECT * FROM tbClientes WHERE MONTH(FDNAC) = 09; #POR MES
SELECT * FROM tbClientes WHERE DAY(FDNAC) = 20; #POR DIA
SELECT * FROM tbVendedores WHERE YEAR(FDADMISION) >= 2016;

#FILTROS COMPUESTOS
SELECT * FROM tbProducto WHERE ENVASE = "BOTELLA DE VIDRIO" OR ENVASE = "LATA"; # OR = O.. 
SELECT * FROM tbProducto WHERE (ENVASE = "BOTELLA DE VIDRIO" OR ENVASE = "BOTELLA PET") OR (PRECIO_LISTA > 5 AND PRECIO_LISTA < 15);
SELECT * FROM tbVendedores WHERE (YEAR(FDADMISION) < 2016) AND (VACACIONES = 1);


SELECT NOMBRE, MATRICULA FROM tbVendedores;

#Fin